### ISSUE TITLE
checksum mismatch

### ISSUE THREAD

**Issue by 2019jack** [bnb-chain/greenfield-sp-standard-test#6]
commit 162667604358c43f16896861b80c676041c6da5b

command: go mod tidy

verifying github.com/consensys/gnark-crypto@v0.7.0: checksum mismatch
        downloaded: h1:rwdy8+ssmLYRqKp+ryRRgQJl/rCq2uv+n83cOydm5UE=
        go.sum:     h1:pxGDRS9ZNRQaXlAJPigJ1Nc9HPwCPKrJjUF/0SgNFmA=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.

**Comment by 2019jack** [comment]
@MockY-B can you check?

**Comment by cyber-y** [comment]
fixed : https://github.com/bnb-chain/greenfield-sp-standard-test/pull/5/files

**Comment by 2019jack** [comment]
> fixed : https://github.com/bnb-chain/greenfield-sp-standard-test/pull/5/files

execute command: `go test -v -run TestSPFunctional -timeout 30m`

error:
```
# runtime/cgo
_cgo_export.c:3:10: fatal error: stdlib.h: No such file or directory
    3 | #include <stdlib.h>
      |          ^~~~~~~~~~
compilation terminated.
FAIL    github.com/bnb-chain/greenfield-sp-standard-test [build failed]
root@10-7-46-85:/data/greenfield-sp-standard-test# go test -v -run TestSPFunctional -timeout 30m
# runtime/cgo
_cgo_export.c:3:10: fatal error: stdlib.h: No such file or directory
    3 | #include <stdlib.h>
      |          ^~~~~~~~~~
compilation terminated.
FAIL    github.com/bnb-chain/greenfield-sp-standard-test [build failed]
```

**Comment by cyber-y** [comment]
Have you downloaded "build-essential" and try again?

**Comment by 2019jack** [comment]
> go test -v -run TestSPFunctional -timeout 30m

`go test -v -run TestSPFunctional -timeout 30m`

error:
```

?       github.com/bnb-chain/greenfield-sp-standard-test/config [no test files]

```

config.yml

![sp](https://github.com/bnb-chain/greenfield-sp-standard-test/assets/49616005/7b90e64f-8942-42b7-83a3-31b7a7d6d347)

**Comment by MockY-B** [comment]
Have you modified the directory structure? This is not a problem with the content of the config file
